# Generated by Django 4.2.14 on 2024-07-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0002_remove_detection_image_alter_user_stellar_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='stellar_address',
            field=models.CharField(blank=True, max_length=56, null=True, unique=True),
        ),
    ]
